[package]
name = "netfetch"
version = "0.0.3"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2024"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11"
serde_yaml = "0.9.16"
ciborium = "0.2.2"
tokio-stream = { version = "0.1", features = ["fs"] }
tracing = "0.1.37"
async-channel = "2.3.1"
bytes = "1.10"
arrayref = "0.3"
byteorder = "1.5"
futures-util = "0.3"
md-5 = "0.10.5"
hex = "0.4.3"
regex = "1.8.4"
axum = "0.8.1"
http-body = "1"
url = "2.5"
chrono = "0.4"
time = { version = "0.3.40", features = ["serde"] }
humantime = "2.1.0"
humantime-serde = "1.1.1"
pin-project = "1"
lazy_static = "1"
libc = "0.2"
slidebuf = "0.0.1"
dashmap = "6.0.1"
hashbrown = "0.15.2"
smallvec = "1.13.2"
autoerr = "0.0.3"
log = { path = "../log" }
series = { path = "../../daqbuf-series", package = "daqbuf-series" }
serieswriter = { path = "../serieswriter" }
stats = { path = "../stats" }
scywr = { path = "../scywr" }
dbpg = { path = "../dbpg" }
ingest-linux = { path = "../ingest-linux" }
err = { path = "../../daqbuf-err", package = "daqbuf-err" }
netpod = { path = "../../daqbuf-netpod", package = "daqbuf-netpod" }
items_0 = { path = "../../daqbuf-items-0", package = "daqbuf-items-0" }
items_2 = { path = "../../daqbuf-items-2", package = "daqbuf-items-2" }
streams = { path = "../../daqbuf-streams", package = "daqbuf-streams" }
ca_proto = { path = "../../daqbuf-ca-proto", package = "daqbuf-ca-proto" }
ca-proto-tokio = { path = "../../daqbuf-ca-proto-tokio", package = "daqbuf-ca-proto-tokio" }
serde-helper = { path = "../../daqbuf-serde-helper", package = "daqbuf-serde-helper" }
taskrun = { path = "../../daqbuffer/crates/taskrun" }
mrucache = { path = "../mrucache" }
batchtools = { path = "../batchtools" }

[features]
disabled = []
