[package]
name = "stats"
version = "0.0.1-a.0"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[lib]
path = "src/stats.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
rand_xoshiro = "0.7.0"
stats_types = { path = "../stats_types" }
stats_proc = { path = "../stats_proc" }
log = { path = "../../daqbuf-log", package = "log" }
mettrics = { version = "0.0.7", path = "../../mettrics" }
ca_proto = { path = "../../daqbuf-ca-proto", package = "daqbuf-ca-proto" }
